dataset:
  robot_names:
    - 'robotiq_3finger'

  debug_object_names: null

  batch_size: 100  # sample per object
  num_workers: 16
  object_pc_type: 'random'  # 'fixed', 'random', 'partial'

model:
  vqvae_cfg:
    n_embeddings: 1024
    embedding_dim: 16
    num_point: 25
    num_dim: 64
    local_decode_pts: 40
    beta: 0.25
  vqvae_pretrain: 'ckpt/vqvae.ckpt'
  object_patch: 25
  max_link_node: 25
  robot_links:
    barrett: 10
    allegro: 21
    shadowhand: 17
    robotiq_3finger: 13
    ezgripper: 5
  inference_config:
    inference_mode: 'unconditioned'  # unconditioned, palm_conditioned
  bps_config:
    bps_type: 'random_uniform'
    n_bps_points: 124
    radius: 1.0
    n_dims: 3
  N_t_training: 10
  diffusion_config:
    scheduling: linear
    M: 1000
    beta_min: 0.0001
    beta_max: 0.02
    ddim_steps: 20
    ddim_eta: 1.0
    lambda: 0.2
  denoiser_config:
    t_embed_dim: 200
    V_object_dims: [3, 1, 64]
    V_robot_dims: [3, 3, 128]
    E_or_dims: [3, 3]
    E_rr_dims: [3, 3]
    v_conv_dim: 384
    e_conv_dim: 384
    num_layers: 6
    c_atten_head: 32
    v_out_hidden_dims: [256, 128]
    e_out_hidden_dims: [256, 128]
    se3_out_dim: [3, 3]
  embodiment:
    - 'allegro'
    - 'barrett'
    - 'shadowhand'
    - 'robotiq_3finger'
    - 'ezgripper'
  mode: "test"
  loss_config:
    trans_weight: 1.0
    rot_weight: 1.0

test:
  embodiment: "robotiq_3finger"
  ckpt: "graph_exp/tro_3hand/ckpt/20.pth"
  save_dir: "graph_exp/tro_3hand/robotiq_3finger-unconditioned-test"
  gpu: 2
  split_batch_size: 100    # sample per split
  