model_type: 'diff_v3_ce'

dataset:
  robot_names:
    - 'leaphand'
  debug_object_names: null
  batch_size: 100
  num_workers: 16
  object_pc_type: 'random'

model:
  vqvae_cfg:
    n_embeddings: 1024
    embedding_dim: 16
    num_point: 25
    num_dim: 64
    local_decode_pts: 40
    beta: 0.25
  vqvae_pretrain: 'ckpt/vqvae.ckpt'
  object_patch: 25
  max_link_node: 25
  robot_links:
    barrett: 10
    allegro: 21
    shadowhand: 17
    leaphand: 17
    robotiq_3finger: 13
    ezgripper: 5
    xhand: 13
  inference_config:
    inference_mode: 'unconditioned' # unconditioned, palm_conditioned, no_object
  bps_config:
    bps_type: 'random_uniform'
    n_bps_points: 124
    radius: 1.0
    n_dims: 3
  N_t_training: 10
  diffusion_config:
    scheduling: linear
    M: 1000
    beta_min: 0.0001
    beta_max: 0.02
    ddim_steps: 100
    ddim_eta: 1.0
    lambda: 0.2
  denoiser_config:
    t_embed_dim: 200
    V_object_dims: [3, 1, 64]
    V_robot_dims: [3, 3, 128]
    v_conv_dim: 384
    num_heads: 16
    ffn_dim: 1536
    num_layers: 6
    v_out_hidden_dims: [256, 128]
    se3_out_dim: [3, 3]
  ce_config:
    p_uncond: 0.1
    no_gt_robot_names:
      - 'leaphand'
    guidance_scale: 1.5
    no_gt_loss_weight: 1.0
  embodiment:
    - 'allegro'
    - 'barrett'
    - 'shadowhand'
    - 'leaphand'
    - 'robotiq_3finger'
  mode: 'test'
  loss_config:
    trans_weight: 1.0
    rot_weight: 1.0

vis:
  embodiment: 'leaphand'
  ckpt: 'graph_exp/diff_v3_bas_l_ce_v2/ckpt/epoch=299.ckpt'
  split_batch_size: 100
  gpu: 0
  port: 8080
  save_path: null
